title: DNS Toolkit
description: A lightweight Windows utility to test, compare, and switch DNS providers.
theme: jekyll-theme-cayman

# Enable GitHub Pages extras
plugins:
  - jekyll-seo-tag

# Optional neat URLs
markdown: kramdown
